### ISSUE TITLE
Traceback when MkDocs directory is not the repository root

### ISSUE THREAD

**Issue by uliska** [timvink/mkdocs-git-authors-plugin#1]
I am trying to use the `git-authors` plugin with MkDocs in a context where the root of the MkDocs project is not the root of the repository, and this breaks with the following error:

```
Traceback (most recent call last):
  File "/home/uliska/.local/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/home/uliska/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/uliska/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/uliska/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/uliska/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/uliska/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/uliska/.local/lib/python3.7/site-packages/mkdocs/__main__.py", line 162, in build_command
    site_dir=site_dir
  File "/home/uliska/.local/lib/python3.7/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/home/uliska/.local/lib/python3.7/site-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/home/uliska/.local/lib/python3.7/site-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/home/uliska/.local/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 132, in validate
    return self.run_validation(value)
  File "/home/uliska/.local/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 572, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/home/uliska/.local/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 587, in load_plugin
    plugin = Plugin()
  File "/home/uliska/.local/lib/python3.7/site-packages/mkdocs_git_authors_plugin/plugin.py", line 12, in __init__
    self.util = Util()
  File "/home/uliska/.local/lib/python3.7/site-packages/mkdocs_git_authors_plugin/util.py", line 7, in __init__
    self.repo = Repo(path)
  File "/home/uliska/.local/lib/python3.7/site-packages/git/repo/base.py", line 184, in __init__
    raise InvalidGitRepositoryError(epath)
```
This is because
* in `GitAuthorsPlugin` an `Util()` instance is created without path argument
* which in `util.py` defaults to `'.'`, i.e. the current working directory.
* in `pythongit` `Repo()` expects the root directory.

I think that the `GitAuthorsPlugin` should make sure to determine the project's root directory, because I don't think it is an invalid case to have the project root differ from the repository root.

**Comment by uliska** [comment]
`git rev-parse --show-toplevel` will return the toplevel directory of a repository.

However, within Git submodules this will show the root of the submodule, and I haven't tested yet whether this will help the situation.

**Comment by timvink** [comment]
Thanks for the report & investigation! 

Will spend some time this weekend/next week to look into it & release a new version.

**Comment by timvink** [comment]
`mkdocs` give the absolute path to the markdown file. We should be able to `cd` there in order to run a `git blame`. Perhaps the dependency on `GitPython` can be dropped entirely, making this plugin a bit lighter.

Before I work on this, I am refactoring the tests for https://github.com/timvink/mkdocs-git-revision-date-localized-plugin, which I can then re-use here to easily write a test for this situation.

**Comment by uliska** [comment]
> Perhaps the dependency on GitPython can be dropped entirely, making this plugin a bit lighter.

Will this plugin ever need to do more than a handful (if at all) of Git commands? If not it might be more straightforward to simply call git through the shell directly, indeed.

We're having similar considerations over at Frescobaldi ([GitHub repo](https://github.com/frescobaldi/frescobaldi)) where we're aiming at offering Git support for the program itself (you can run it from different branches to test pull requests), for edited documents (to encourage users to version their files), and to install packages and other stuff. https://github.com/frescobaldi/frescobaldi/pull/1197 is one such attempt, although it's in that case trying to create an abstraction for a repository on *Github*, not the Git repo itself. We have our custom repo implementations here: https://github.com/frescobaldi/frescobaldi/tree/master/frescobaldi_app/vcs but are not sure whether it might be a good idea to let some external dependency (like GitPython) do the low-level work.

**Comment by uliska** [comment]
Independently from all this: Any such Git error (The project just might not be inside a Git repo, Git is not installed, (more?)) should not cause the plugin (and through that MkDocs) to crash but print a warning to the console and nothing into the document.

**Comment by uliska** [comment]
I'll have a look today. Since I need this plugin for my work (documenting a university LMS, and we want to use the git-authors output as an incentive to participate in this effort) I may justify using some of my working hours for that.

**Comment by uliska** [comment]
Probably this should be reopened? It was closed through a commit message but it was saud there should be a unit test.

**Comment by timvink** [comment]
And the unit tests are now failing. Will update github actions so they already run on PR, then I'll fix.

**Comment by uliska** [comment]
I'v run into the situation that I'm trying to suggest a replacement for GitPython. I'll open a Pull Request today.

**Comment by timvink** [comment]
Sounds good!

I'd like to keep using `GitPython` in the tests , so remember to add it here as a dependency to `tests/test_requirements.txt`

**Comment by uliska** [comment]
> I'd like to keep using GitPython in the tests 

Yes, that's what I thought too.
