### ISSUE TITLE
File not found errors

### ISSUE THREAD

**Issue by njnatale-lm** [timvink/mkdocs-git-authors-plugin#88]
Recently, I'm unable to use the plugin at all; I'm curious if it is related to a Git version change on my Windows device (2.45.1; I think I was on 2.43 before this).

The error I'm getting:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<path>\repos\docs2\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "<path>\repos\docs2\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\mkdocs\__main__.py", line 268, in serve_command
    serve.serve(**kwargs)
  File "<path>\repos\docs2\Lib\site-packages\mkdocs\commands\serve.py", line 85, in serve
    builder(config)
  File "<path>\repos\docs2\Lib\site-packages\mkdocs\commands\serve.py", line 67, in builder
    build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
  File "<path>\repos\docs2\Lib\site-packages\mkdocs\commands\build.py", line 265, in build
    config = config.plugins.on_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\mkdocs\plugins.py", line 587, in on_config
    return self.run_event('config', config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\mkdocs\plugins.py", line 566, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\mkdocs_git_authors_plugin\plugin.py", line 70, in on_config
    self._repo = Repo()
                 ^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\mkdocs_git_authors_plugin\git\repo.py", line 11, in __init__
    self._root = self.find_repo_root()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "<path>\repos\docs2\Lib\site-packages\mkdocs_git_authors_plugin\git\repo.py", line 93, in find_repo_root
    cmd.run()
  File "<path>\repos\docs2\Lib\site-packages\mkdocs_git_authors_plugin\git\command.py", line 61, in run
    p = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I'm running version `0.9.0` of the plugin.

**Comment by njnatale-lm** [comment]
I've tracked this down with some debugging; it appears the deployment my machine received for the latest version of Git failed to add the directory for `git` onto my `PATH` variable, thus causing this issue.

**Comment by timvink** [comment]
Thanks for sharing the resolution also!
