### ISSUE TITLE
MkApi 3.x breaks this plugin

### ISSUE THREAD

**Issue by twsl** [timvink/mkdocs-git-authors-plugin#91]
```
DEBUG   -  Running `files` event from plugin 'mkapi'
DEBUG   -  Running `files` event from plugin 'git-authors'
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 288, in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    files = config.plugins.on_files(files, config=config)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/plugins.py", line 593, in on_files
    return self.run_event('files', files, config=config)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mkdocs_git_authors_plugin/plugin.py", line 124, in on_files
    if path.endswith(".md"):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
Haven't really checked anything in depth yet, but just updating mkapi from v2 to v3 causes the docs pipeline to fail here.
I assume it could be related to files [alternatively stored in memory](https://www.mkdocs.org/dev-guide/api/#mkdocs.structure.files.File)

**Comment by twsl** [comment]
Apparently I am right: https://daizutabi.github.io/mkapi/usage/page/#simple-navigation-setup:~:text=Since%20MkAPI%20version%203.0%2C%20files%20generated%20by%20MkAPI%20are%20stored%20in%20memory%20and%20not%20written%20to%20disk.
